sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t sukhwantprafulli/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true sukhwantprafulli/docker-react npm run test -- --coverage
